<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
   targetNamespace="http://www.myservice.com/wfs"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
   xmlns:wfs-http="http://www.opengis.net/wfs/http"
   xmlns:wfs-http-kvp="http://www.opengis.net/wfs/http/kvp"
   xmlns:wfs-soap="http://www.opengis.net/wfs/soap"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

   <wsdl:documentation xmlns:dc="http://purl.org/dc/elements/1.1/">
      <dc:date>2004-06-07</dc:date>
      <dc:description>
         This WSDL document defines the service-specific properties
         of a MyService WFS implementation; it specifies available
         endpoints and alternative bindings.
      </dc:description>
   </wsdl:documentation>

   <wsdl:import namespace="http://www.opengis.net/wfs/soap"
                location="./wfs-soap-bindings.wsdl"/>
   <wsdl:import namespace="http://www.opengis.net/wfs/http"
                location="./wfs-http-bindings.wsdl"/>
   <wsdl:import namespace="http://www.opengis.net/wfs/http/kvp"
                location="./wfs-kvp-bindings.wsdl"/>

   <wsdl:service name="WFS-www.myservice.com">
      <wsdl:documentation>
         A WFS-1.1 implementation. Includes alternative SOAP bindings
         for the WFS interfaces.
      </wsdl:documentation>
      <wsdl:port name="wfs-SOAP-Port" binding="wfs-soap:wfs-SOAP">
         <soap:address
               location="http://www.myservice.com/wfs-soap/services/WFSSOAP"/>
      </wsdl:port>
      <wsdl:port name="wfs-POST-Port" binding="wfs-http:wfs-POST">
         <http:address location="http://www.myservice.com/"/>
      </wsdl:port>
      <wsdl:port name="wfs-GET-Port" binding="wfs-http-kvp:wfs-GET">
         <http:address location="http://www.myservice.com/"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
