<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
   targetNamespace="http://www.myservice.com/wfs"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
   xmlns:wfs-http="http://www.opengis.net/wfs/http">
   <wsdl:documentation xmlns:dc="http://purl.org/dc/elements/1.1/">
      <dc:date>2004-05-26</dc:date>
      <dc:description>
         This WSDL document defines the service-specific properties
         of a MyService WFS implementation; it specifies available
         endpoints and alternative bindings.
      </dc:description>
   </wsdl:documentation>

   <wsdl:import namespace="http://www.opengis.net/wfs/http"
                location="./wfs-http-bindings.wsdl"/>

   <wsdl:service name="WFS-www.myservice.com">
      <wsdl:documentation>A WFS-1.1 implementation.</wsdl:documentation>
      <wsdl:port name="wfs-POST-Port" binding="wfs-http:wfs-POST">
         <http:address location="http://www.myservice.com/"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
