
// This file has been generated by the GUI designer. Do not modify.

namespace TestGtk
{
    public partial class MainWindow
    {
        private global::Gtk.Fixed fixed1;

        private global::Gtk.EventBox eventbox1;

        private global::Gtk.Image image3;

        private global::Gtk.Label label1;

        private global::Gtk.RadioButton radZoomIn;

        private global::Gtk.RadioButton radPan;

        private global::Gtk.RadioButton radZoomOut;

        protected virtual void Build()
        {
            global::Stetic.Gui.Initialize(this);
            // Widget MainWindow
            this.Name = "MainWindow";
            this.Title = "MainWindow";
            this.WindowPosition = ((global::Gtk.WindowPosition) (4));
            // Container child MainWindow.Gtk.Container+ContainerChild
            this.fixed1 = new global::Gtk.Fixed();
            this.fixed1.Name = "fixed1";
            this.fixed1.HasWindow = false;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.eventbox1 = new global::Gtk.EventBox();
            this.eventbox1.WidthRequest = 800;
            this.eventbox1.HeightRequest = 500;
            this.eventbox1.Name = "eventbox1";
            // Container child eventbox1.Gtk.Container+ContainerChild
            this.image3 = new global::Gtk.Image();
            this.image3.Events = ((global::Gdk.EventMask) (256));
            this.image3.Name = "image3";
            this.eventbox1.Add(this.image3);
            this.fixed1.Add(this.eventbox1);
            global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild) (this.fixed1[this.eventbox1]));
            w2.X = 13;
            w2.Y = 52;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.label1 = new global::Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = "Map x,y";
            this.fixed1.Add(this.label1);
            global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild) (this.fixed1[this.label1]));
            w3.X = 695;
            w3.Y = 19;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.radZoomIn = new global::Gtk.RadioButton("Zoom In");
            this.radZoomIn.CanFocus = true;
            this.radZoomIn.Name = "radZoomIn";
            this.radZoomIn.DrawIndicator = true;
            this.radZoomIn.UseUnderline = true;
            this.radZoomIn.Group = null;;
            this.fixed1.Add(this.radZoomIn);
            global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild) (this.fixed1[this.radZoomIn]));
            w4.X = 306;
            w4.Y = 13;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.radPan = new global::Gtk.RadioButton("Pan");
            this.radPan.CanFocus = true;
            this.radPan.Name = "radPan";
            this.radPan.DrawIndicator = true;
            this.radPan.UseUnderline = true;
            this.radPan.Group = this.radZoomIn.Group;
            this.fixed1.Add(this.radPan);
            global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild) (this.fixed1[this.radPan]));
            w5.X = 242;
            w5.Y = 13;
            // Container child fixed1.Gtk.Fixed+FixedChild
            this.radZoomOut = new global::Gtk.RadioButton("Zoom Out");
            this.radZoomOut.CanFocus = true;
            this.radZoomOut.Name = "radZoomOut";
            this.radZoomOut.DrawIndicator = true;
            this.radZoomOut.UseUnderline = true;
            this.radZoomOut.Group = this.radZoomIn.Group;
            this.fixed1.Add(this.radZoomOut);
            global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild) (this.fixed1[this.radZoomOut]));
            w6.X = 401;
            w6.Y = 12;
            this.Add(this.fixed1);
            if ((this.Child != null))
            {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 838;
            this.DefaultHeight = 599;
            this.Show();
            this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.eventbox1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.EventBoxButtonPress);
        }
    }
}
