<?xml version="1.0" encoding="ISO-8859-1"?>
<wsdl:definitions
   targetNamespace="http://www.myservice.com/wfs/2.0"
   xmlns:wfs-http="http://www.opengis.net/wfs/http/kvp/2.0"
   xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <wsdl:documentation xmlns:dc="http://purl.org/dc/elements/1.1/">
      <dc:date>2008-08-31</dc:date>
      <dc:description>
         This WSDL document defines the service-specific properties
         of a MyService WFS implementation; it specifies available endpoints
         and alternative bindings.
      </dc:description>
   </wsdl:documentation>
   <wsdl:import namespace="http://www.opengis.net/wfs/http/kvp/2.0"
      location="./wfs-kvp-bindings.wsdl"/>
   <wsdl:service name="WFS-www.myservice.com">
      <wsdl:documentation>A WFS-2.0 implementation.</wsdl:documentation>
      <wsdl:port name="wfs-GET-Port" binding="wfs-http:wfs-GET">
         <http:address location="http://www.myservice.com/"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
